# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-34LNVHCGDT'

menu:
- {name: 'Insights / 觀點', url: 'insights'}
- {name: 'Services/服務項目',url: 'services'}
- {name: 'Sample Posts/案例分享',url: 'sample-posts'}
- {name: 'Resource/資源',url: 'resource'}
- {name: 'About/關於',url: 'about'}
- {name: 'Contact/聯絡我們',url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/szuhui-huang/'}
- {icon: 'facebook', link: 'https://www.facebook.com/ema721'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:ema0721@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
